runtime: python39

automatic_scaling:
  max_instances: 1

handlers:
- url: /
  static_files: static/index.html
  upload: static/index.html
  secure: always

- url: /static
  static_dir: static
  secure: always

- url: /.*
  script: auto
  secure: always
